Filter merge test
WildCodeSchool/reims-0919-js-pudding-arsenic pull request #2
Opened 2019-10-25 08:33 UTC by ArchStanton987

Dear reviewers,

This is our first version of FoodRoulette. As you'll notice, it features several components at once. It includes "home" (homepage), filter pages for both cocktails and pizza, and the page which displays ingredients.
So far, buttons are not yet functional but we have now a global insight. Ingredients also displays from 3 to 7 cards (randomly, which resets when you refresh the page). So far, ingredients displays doesn't come directly from the API, but in an array stored in app.js.
From this scaled mockup we'll be able to make components alive during our second sprint.

Best regards,

FoodRoullette Dev Team

2019-10-25 09:01 UTC, erabin05 requested changes
Some changes to do : see comments to know what.
Next time try to have less files in your PR (30 files :'( )

2019-10-25 09:01 UTC, erabin05 commented on README.md
> -# reims-0919-js-pudding-arsenic
Personalise the README.md to introduce your projects : quick description of what it is and team members

2019-10-25 09:01 UTC, erabin05 commented on src/App.js
> +		}
render is not the place to put all this code.
Some can be in a state, some in methods or directly in JSX

2019-10-25 09:01 UTC, erabin05 commented on src/App.js
> +		console.log(ingredientArray)
Remove console.log() for PR

2019-10-25 09:01 UTC, erabin05 commented on src/components/Home.js
> +class Home extends React.Component {
If the Component is stateless it must be a function

2019-10-25 09:01 UTC, erabin05 commented on src/components/Home.js
> +						{/* <a href="#CocktailFilters">Get a cocktail</a> */}
No dead code in PR

2019-10-25 09:01 UTC, erabin05 commented on src/components/HomeText.js
> +//export default HomeText
Don't need this empty component in PR

2019-10-25 09:01 UTC, erabin05 commented on src/components/ShowIngredients/ShowIngredients.js
> +class ShowIngredients extends React.Component {
Can be a function because stateless

2019-11-05 13:52 UTC, ghost commented on src/components/ShowIngredients/ShowIngredients.js
> +class ShowIngredients extends React.Component {
Is now a function.

2019-11-05 13:52 UTC, ghost commented on src/components/HomeText.js
> +//export default HomeText
Removed.

2019-11-05 13:52 UTC, ghost commented on src/components/Home.js
> +						{/* <a href="#CocktailFilters">Get a cocktail</a> */}
Removed.

2019-11-05 13:52 UTC, ghost commented on src/components/Home.js
> +class Home extends React.Component {
Is now a function.

2019-11-05 13:52 UTC, ghost commented on src/App.js
> +		console.log(ingredientArray)
Removed.

2019-11-05 13:52 UTC, ghost commented on README.md
> -# reims-0919-js-pudding-arsenic
Done.

2019-11-05 13:54 UTC, ArchStanton987 commented on src/App.js
> +		}
This piece of code has been modified : it is now in a component "ShowIngredientList", which calls "ShowIngredients" and is called by "App".

2019-11-06 08:24 UTC, erabin05 approved these changes
Ok

2019-11-06 08:24 UTC, merged